version: '3.8'

volumes:
  registry_data:
    name: registry_data

services:
  
  registry:
    image: registry:2
    container_name: registry
    environment:
      - REGISTRY_HTTP_PREFIX=/registry/
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry