version: '3.8'

networks:
  jenkins-network:
    name: jenkins
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  data:
    name: jenkins-data
  certs:
    name: jenkins-docker-certs
  registry_data:
    name: registry_data

services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      jenkins-network:
        ipv4_address: 172.20.0.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_certs:/etc/nginx/certs:ro
    restart: always

  dind:
    container_name: jenkins-docker
    build:
      dockerfile: ./Dind.Dockerfile
    privileged: true
    restart: unless-stopped
    networks:
      jenkins-network:
        aliases:
          - docker
        ipv4_address: 172.20.0.3
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    container_name: jenkins
    build:
      dockerfile: ./Jenkins.Dockerfile
    restart: unless-stopped
    networks:
      jenkins-network:
        ipv4_address: 172.20.0.4
    volumes:
      - data:/var/jenkins_home
      - certs:/certs/client:ro
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
  
  registry:
    image: registry:2
    container_name: registry
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    networks:
      jenkins-network:
        ipv4_address: 172.20.0.5
    volumes:
      - registry_data:/var/lib/registry
      - './certs:/certs'